## Practice

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [1]:
#1
import numpy as np
a= np.ones(10,dtype=float)
b = np.tile(np.array([1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),(8,1))
np.vstack([np.vstack([a,b]),a])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [47]:
#2
a = np.tile(np.arange(5),(5,1))
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [48]:
#3
a = np.array([0., 1., 0., 1., 0., 1., 0., 1.])
b = np.array([1., 0., 1., 0., 1., 0., 1., 0.])
np.tile(np.vstack([a,b]),(3,1))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [49]:
#4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix 

In [51]:
#5
from sklearn.preprocessing import normalize
from numpy.random import default_rng
x = default_rng(42).random((2,3))
print(x)
normalize(x, axis=1, norm='l1')

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


array([[0.37363326, 0.21187196, 0.41449478],
       [0.3946247 , 0.05329282, 0.55208249]])

6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [52]:
#6
x = np.random.random((10,2))
r = np.sqrt(x[:,0]**2+x[:,1]**2)
t = np.arctan2(x[:,1],x[:,0])
r,t

(array([0.84518951, 1.04297312, 0.55501544, 1.09640149, 0.47076657,
        1.18919074, 0.55401433, 0.71929909, 1.02344885, 0.82960968]),
 array([0.29008247, 0.68185846, 0.29020919, 0.83915633, 1.266724  ,
        0.78922915, 1.49805552, 0.70127632, 1.22409614, 1.47367904]))

7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [53]:
#7
v = np.array([1, 2, 3, 4, 5])
z = np.zeros(3)
i = np.arange(1,len(v))*4-3
# i = np.arange(1,3)
#print(i)
for u in range(4):
    v = np.insert(v,i[u],z)
print(v)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [54]:
#8
print(0 * np.nan)

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(np.nan in set([np.nan]))

0.3 == 3 * 0.1

nan
False
False
nan
True


False

9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [41]:
#9
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Wiman\AppData\Local\Temp\ipykernel_18192\2370070070.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Wiman\AppData\Local\Temp\ipykernel_18192\2370070070.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Wiman\AppData\Local\Temp\ipykernel_18192\2370070070.py:6: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))
